name: docker push containers to dockerhub

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  docker-push-containers-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: build docker image and push to DockerHub
        uses: senzing-factory/github-action-docker-buildx-build@v1
        with:
          build-options: "--push"
          image-repository: senzing/apt
          image-tag: ${{ github.ref_name }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
